package br.com.bortoletto.ecommerce.entities;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encomenda generated by hbm2java
 */
@Entity
@Table(name = "encomenda", schema = "pizzaria")
public class Encomenda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3037874294916300659L;
	private Integer id;
	private Endereco endereco;
	private FormaPagamento formaPagamento;
	private Date dataEncomenda;
	private BigDecimal valorTotal;
	private Set<StatusTransicaoEncomenda> statusTransicaoEncomenda;

	public Encomenda() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_endereco")
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_forma_pagamento")
	public FormaPagamento getFormaPagamento() {
		return this.formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_encomenda", nullable = false, length = 29)
	public Date getDataEncomenda() {
		return this.dataEncomenda;
	}

	public void setDataEncomenda(Date dataEncomenda) {
		this.dataEncomenda = dataEncomenda;
	}

	@Column(name = "valor_total", nullable = false, precision = 10)
	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "encomenda")
	public Set<StatusTransicaoEncomenda> getStatusTransicaoEncomenda() {
		return statusTransicaoEncomenda;
	}

	public void setStatusTransicaoEncomenda(Set<StatusTransicaoEncomenda> statusTransicaoEncomenda) {
		this.statusTransicaoEncomenda = statusTransicaoEncomenda;
	}

}
