package br.com.bortoletto.ecommerce.entities;
// Generated 03/06/2017 00:11:10 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name = "forma_pagamento", schema = "pizzaria")
public class FormaPagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1543333765478112637L;
	private Integer id;
	private String nomeFormaPagamento;

	public FormaPagamento() {
		//
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome_forma_pagamento", nullable = false, length = 50)
	public String getNomeFormaPagamento() {
		return this.nomeFormaPagamento;
	}

	public void setNomeFormaPagamento(String nomeFormaPagamento) {
		this.nomeFormaPagamento = nomeFormaPagamento;
	}

}
