package br.com.bortoletto.ecommerce.entities;
// Generated 03/06/2017 00:11:10 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImagemProduto generated by hbm2java
 */
@Entity
@Table(name = "imagem_produto", schema = "pizzaria")
public class ImagemProduto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4730542560020512207L;
	private Integer id;
	private Produto produto;
	private String urlImagem;

	public ImagemProduto() {
		//
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produto")
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "url_imagem", nullable = false)
	public String getUrlImagem() {
		return this.urlImagem;
	}

	public void setUrlImagem(String urlImagem) {
		this.urlImagem = urlImagem;
	}

}
