package br.com.bortoletto.ecommerce.entities;
// Generated 03/06/2017 00:11:10 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "produto", schema = "pizzaria")
public abstract class Produto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6780164200845976906L;
	private Integer id;
	private String nome;
	private String descricao;
	private BigDecimal preco;
	private Boolean ativo;
	private TipoProduto tipoProduto;
	private ImagemProduto imagemProduto;

	public Produto() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "preco", nullable = false, precision = 10)
	public BigDecimal getPreco() {
		return this.preco;
	}

	public void setPreco(BigDecimal preco) {
		this.preco = preco;
	}

	@Column(name = "ativo", nullable = false)
	public Boolean isAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	@Column(name = "imagem_produto")
	public ImagemProduto getImagemProduto() {
		return imagemProduto;
	}

	public void setImagemProduto(ImagemProduto imagemProduto) {
		this.imagemProduto = imagemProduto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tipo_produto")
	public TipoProduto getTipoProduto() {
		return tipoProduto;
	}

	public void setTipoProduto(TipoProduto tipoProduto) {
		this.tipoProduto = tipoProduto;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public String toString() {
		return "Produto [id=" + id + ", nome=" + nome + ", descricao=" + descricao + ", preco=" + preco + ", ativo="
				+ ativo + ", tipoProduto=" + tipoProduto + ", imagemProduto=" + imagemProduto + "]";
	}

}
