package br.com.bortoletto.ecommerce.entities;
// Generated 03/06/2017 00:11:10 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatusTransicaoEncomenda generated by hbm2java
 */
@Entity
@Table(name = "status_transicao_encomenda", schema= "pizzaria")
public class StatusTransicaoEncomenda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4172351689123373843L;
	private Integer id;
	private Encomenda encomenda;
	private StatusEncomenda statusEncomenda;
	private Integer idTransicaoAnterior;
	private Date dataTransicao;
	private Boolean ultimaTransicao;

	public StatusTransicaoEncomenda() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_encomenda")
	public Encomenda getEncomenda() {
		return this.encomenda;
	}

	public void setEncomenda(Encomenda encomenda) {
		this.encomenda = encomenda;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_status_encomenda")
	public StatusEncomenda getStatusEncomenda() {
		return this.statusEncomenda;
	}

	public void setStatusEncomenda(StatusEncomenda statusEncomenda) {
		this.statusEncomenda = statusEncomenda;
	}

	@Column(name = "id_transicao_anterior")
	public Integer getIdTransicaoAnterior() {
		return this.idTransicaoAnterior;
	}

	public void setIdTransicaoAnterior(Integer idTransicaoAnterior) {
		this.idTransicaoAnterior = idTransicaoAnterior;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_transicao", nullable = false, length = 29)
	public Date getDataTransicao() {
		return this.dataTransicao;
	}

	public void setDataTransicao(Date dataTransicao) {
		this.dataTransicao = dataTransicao;
	}

	@Column(name = "ultima_transicao")
	public Boolean getUltimaTransicao() {
		return this.ultimaTransicao;
	}

	public void setUltimaTransicao(Boolean ultimaTransicao) {
		this.ultimaTransicao = ultimaTransicao;
	}

}
