package br.com.bortoletto.ecommerce.entities;
// Generated 03/06/2017 00:11:10 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StatusEncomenda generated by hbm2java
 */
@Entity
@Table(name = "status_encomenda", schema= "pizzaria")
public class StatusEncomenda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7503881259255127799L;
	private Integer id;
	private String nomeStatus;

	public StatusEncomenda() {
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome_status", nullable = false, length = 50)
	public String getNomeStatus() {
		return this.nomeStatus;
	}

	public void setNomeStatus(String nomeStatus) {
		this.nomeStatus = nomeStatus;
	}
}
